{
    'name': "POS Retail Management",
    'version': '5.1.0',
    'category': 'Point of Sale',
    'author': 'TL Technology',
    'live_test_url': 'http://posodoo.com/web/signup',
    'price': '350',
    'website': 'http://posodoo.com',
    'sequence': 0,
    'depends': [
        'sale_stock',
        'account',
        'point_of_sale',
        'bus',
        'stock',
        'purchase',
        'mrp',
        'product_expiry'
    ],
    'demo': ['demo/demo_data.xml'],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_menu.xml',
        'reports/pos_manufacturing_report.xml',
        'reports/pos_tracking_client.xml',
        'reports/pos_sale_analytic.xml',
        'reports/report_pos_order.xml',
        'datas/cache_data.xml',
        'datas/email_template.xml',
        'datas/customer.xml',
        'datas/barcode_rule.xml',
        'datas/pos_loyalty_category.xml',
        'datas/product.xml',
        'datas/stock_picking_type.xml',
        'datas/pos_bus.xml',
        'import/import_libraties.xml',
        'views/pos_config.xml',
        'views/product.xml',
        'views/pos_order.xml',
        'views/sale_order.xml',
        'views/pos_loyalty.xml',
        'views/res_partner_credit.xml',
        'views/res_partner.xml',
        'views/res_users.xml',
        'views/pos_promotion.xml',
        'views/account_journal.xml',
        'views/pos_voucher.xml',
        'views/pos_bus.xml',
        'views/mrp_production.xml',
        'views/pos_sms.xml',
        'views/pos_tag.xml',
        'views/pos_note.xml',
        'views/pos_combo_item.xml',
        'views/product_variant.xml',
        'views/product_barcode.xml',
        'views/stock_production_lot.xml',
        'views/pos_quickly_payment.xml',
        'views/pos_global_discount.xml',
        'views/account_invoice.xml',
        'views/purchase_order.xml',
        'wizards/account_invoice_refund.xml',
        'wizards/sale_order_line_insert.xml',
    ],
    'qweb': [
        'static/src/xml/*.xml'
    ],
    "currency": 'EUR',
    'installable': True,
    'application': True,
    'images': ['static/description/icon.png'],
    'support': 'thanhchatvn@gmail.com',
    "license": "OPL-1",
}
